### ISSUE TITLE
How to change code snippets theme

### ISSUE THREAD

**Issue by vasily-kirichenko** [tpetricek/FSharp.Formatting#254]
Is it possible to tune the theme used for code snippets a bit? It's great if a light theme would available, but a dark one with a lighter background would be also ok.

**Comment by tpetricek** [comment]
Having more standard styles (so that people can choose) would be nice.

We could do that just by adding another file (say `styles-light.css`) to [this folder](https://github.com/tpetricek/FSharp.Formatting/tree/master/docs/files/content). I think that will automatically put it into the NuGet package too.

(Although, the users of F# Formatting will then have to choose it - in ProjectScaffold, that would mean changing [this line](https://github.com/fsprojects/ProjectScaffold/blob/master/docs/tools/templates/template.cshtml#L15). I guess if we have multiple out-of-the-box templates, we can add a bit about styles into ProjecScaffold docs... Or are you thinking about other contexts?

**Comment by vasily-kirichenko** [comment]
OK, I'll add a `styles-light.css`.
