### ISSUE TITLE
I see dead OctoCats

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#263]
I'm not sure if something broke in FSharp.Formatting or only in PAket but I see two OctoCats:

![image](https://cloud.githubusercontent.com/assets/57396/6108081/7b08048a-b070-11e4-974a-b0f126d18d78.png)

See http://fsprojects.github.io/Paket/reference/paket-nugetv3.html

They seem to link to the same URL

**Comment by forki** [comment]
it seems the whole API page design is broken

![image](https://cloud.githubusercontent.com/assets/57396/6108115/cf6149ce-b070-11e4-8a8b-2561042f4074.png)

**Comment by tpetricek** [comment]
Thanks for reporting - will look into this tomorrow!

**Comment by ovatsus** [comment]
I had this before when upgrading to a diff FSharp.Formatting version, turned out I was missing some css that I needed to refetch from the source

**Comment by forki** [comment]
@ovatsus AFAIK we fetch the CSS directly from the package. I think the issue is that we lost a feature for subfolders. I think I need @tpetricek's help. Could you please try to run `build GenerateDocs` in paket's master? Thanks.

**Comment by forki** [comment]
I assume we have the same issue in ProjectScaffold

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/commit/c283825added049144aea39ed9721bb568e7cb3f fixed it for me, but is this the correct fix?

If yes, we probably need to do the same here: 
https://github.com/fsprojects/ProjectScaffold/blob/master/docs/tools/generate.template#L96

/cc @pblasucci

**Comment by tpetricek** [comment]
Hmm, I think the problem is that the `root` parameter that is passed to F# Formatting was intended to be the URL for the root of the web site. Regardless of where (into what sub-directories) you put the generated `html` files, this is always use exactly as it was - so it pretty much has to be an absolute URL.

Paket uses a relative path (which is set [here](https://github.com/fsprojects/Paket/blob/master/docs/tools/generate.fsx#L16) in the `generate.fsx` scritp), which is causing the troubles. Deedle just has an absolute url [here](https://github.com/BlueMountainCapital/Deedle/blob/master/docs/tools/generate.fsx#L9).

So, I think what Paket is doing currently works, except that [this line](https://github.com/fsprojects/Paket/blob/master/docs/tools/generate.fsx#L86) breaks things when running `generate.fsx` locally, because in that case, the file is still absolute `file://....` (and I'm not sure to what extent relative paths work in a file system...)

**Comment by forki** [comment]
IIRC someone changed this to get local help builds running. The CSS and stuff should always be relative if we want to look at it in offline mode.

**Comment by tpetricek** [comment]
I sent a PR with possible fix and more explanation...

**Comment by forki** [comment]
The octocats are alive!
Thanks.
