### ISSUE TITLE
On latest version, while generating F# Data docs, ~20 chart windows are opened

### ISSUE THREAD

**Issue by ovatsus** [tpetricek/FSharp.Formatting#311]
Didn't happen in previous versions, no chart windows would pop up
Relevant code is here: https://github.com/fsharp/FSharp.Data/blob/master/docs/tools/generate.fsx#L99

**Comment by tpetricek** [comment]
Hmm, yes, this is caused by more clever handling of the `fsi` object (more correct, but we were relying on this not working). 

@matthid - Do you think your wrapper library could provide a way of choosing what `fsi` object we want? (Either the one that forwards the calls, or one that ignores everything?)

**Comment by matthid** [comment]
Yes that API is already [there](https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L1115). It should just be the matter stubbing out an implementation with all the members (doing nothing?) and then use the `fsiObj` parameter.

But I'm not sure if we actually should do that, can't we just remove the `RegisterTransformation` call? Why does the broken behavior fix windows popping up?

**Comment by tpetricek** [comment]
When the `FsiEvaluator` evaluates code in the docs (or in the FsLab journal), it runs `#load` to load F# Charting (or FsLab or whatever), which calls `fsi.AddPrinter`.

I believe that the function registered using `fsi.AddPrinter` is then actually called when the snippet being evaluated returns a chart (and so a window with the chart is opened).

Previously, `fsi.AddPrinter` did nothing and so it never registered a handler to open the windows.

So, the question is, should the evaluator in F# Formatting ignore the printers, or should it use them? This is a tricky question - it sounds like using them is a more correct option, but then FsLab (and all other libraries that use `fsi.AddPrinter` and open windows) need to have some way to detect that they are running inside F# Formatting and do not actually do this...

**Comment by matthid** [comment]
Then the correct way would be to remove the `fsi.AddPrinter` calls (and/or make them optional via an API/function call?).

If we change F# Formatting in a way to ignore the `fsi.AddPrinter` call (which is simple to do in itself), we may end up running into this again. For example if someone wants to use `AddPrinter` within a literate documentation file to customize the output (as we can capture and print the stdout, as part of an F# Formatting feature).

How about not referencing [this](https://github.com/fslaborg/FSharp.Charting/blob/master/src/FSharp.Charting.fsx#L24) file from the [documentation](https://github.com/fsharp/FSharp.Data/blob/master/docs/content/library/CsvProvider.fsx#L80). 
Using `#r  FSharp.Charting.dll"` instead of loading the `.fsx` file would probably have the correct behavior?
Otherwise we might want to remove the `AddPrinter` call within the `.fsx` file (and make opt-in or opt-out somehow?).

Would any of those solutions work?

**Comment by tpetricek** [comment]
It would work for F# Data, but I'd prefer if the documentation showed the "recommended way of doing things". In any case, it would not work for FsLab where we are evaluating the following script snippet-by-snippet: https://github.com/fslaborg/FsLab.Templates/blob/journal/Tutorial.fsx

We could make this an optional parameter of `FsiEvaluator` though... Then FsLab can easily turn this off and also disable this in [F# Data here](https://github.com/fsharp/FSharp.Data/blob/master/docs/tools/generate.fsx#L116).

I would even be happy to keep this on by default - we need to disable this in a couple of projects, but not that many...

**Comment by matthid** [comment]
> It would work for F# Data, but I'd prefer if the documentation showed the "recommended way of doing things".

Good point.

> In any case, it would not work for FsLab where we are evaluating the following script snippet-by-snippet: https://github.com/fslaborg/FsLab.Templates/blob/journal/Tutorial.fsx. We could make this an optional parameter of FsiEvaluator though... Then FsLab can easily turn this off and also disable this in F# Data here.

It is probably fine to have an optional parameter called `DisablePrinters` or something like that.
That said:
It still feels like working around the problem instead of fixing it: What if `AddPrinter` had worked from the beginning and couldn't be turned off at all? Depending of `AddPrinter` being a `no-op` feels wrong to me. 

FsLab already has [this](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.fsx#L54) so it isn't even a problem? We could just define `NO_FSI_ADDPRINTER` in `generate.fsx` and it should work (there is already an optional parameter for this in `FsiEvaluator`), right?
Even better, why not make that a feature and always define something like `FSHARP_FORMATTING` or `CONSOLE_ONLY` for these scenarios? FsLab could use it to define printers which are capable to work in console-only environments (which FSF is; this might even come handy for someone sometime)

It basically boils down to your initial suggestion:

> but then FsLab (and all other libraries that use fsi.AddPrinter and open windows) need to have some way to detect that they are running inside F# Formatting and do not actually do this...

I guess that would be one way of doing it and FSF already supports it in the current release. 

Would that work in those scenarios?

**Comment by tpetricek** [comment]
I'm really not sure what the perfect solution here is - but it is worth noting that the printers are actually ignored by the F# Formatting default formatters (at the moment) anyway. 

To get a release with something that we can use right now, I added an option to provide `fsiObj` explicitly to the evaluator and I added a method that creates one which ignores everything:

    open FSharp.Literate
    let fsi = FsiEvaluator(fsiObj = FsiEvaluatorConfig.CreateNoOpFsiObject()) 

@ovatsus Can you update to the latest version and use the above line to create `FsiEvaluator`? This should disable the windows...

**Comment by tpetricek** [comment]
@matthid I don't think this is a perfect solution, but I think that being able to provide your own `fsi` object to the evaluator makes some sense (and it solves the problem we have...)

I had to add a dummy implementation to F# Formatting - if you wanted to move that http://github.com/matthid/Yaaf.FSharp.Scripting, that would be great! (The API is designed to make that possible...)

**Comment by tpetricek** [comment]
I'm not all that happy with this - it is just a hack fixing another hack (the use of `AddPrinter` for showing chart windows...), but I think it is a reasonable option.

**Comment by ovatsus** [comment]
Thanks, this fixed the issue
