### ISSUE TITLE
Unresolved reference to log -> Print source (type/member) of the error.

### ISSUE THREAD

**Issue by haf** [tpetricek/FSharp.Formatting#366]
I'm getting this message:

```
FSharp.Formatting Warning: 0 : Unresolved reference 'log'!
```

What does it mean? Where is it and what's it trying to find?

**Comment by matthid** [comment]
We have some code in place to resolve type member names in the documentation, for example if you write `<c ref='T:Some.Type' />'` we can resolve this to a proper link to the correct documentation for that type/member/module or whatever.

Recently (https://github.com/tpetricek/FSharp.Formatting/pull/330) we can do that for markdown as well via `[Some.Type]`.

The error means, that you somewhere have a reference we could not resolve (for example in this case `[log]` or `<c ref='log' />`). You can try again with the fully qualified name - in case of `<c ref` - or ignore the error because currently we only support type-names - in case of `[log]`/markdown. Or you can of course contribute the code such that we support members and let bindings ;)

**Comment by haf** [comment]
Can you make it print where the warning comes from?

**Comment by matthid** [comment]
I think you can search for `UNRESOLVED(` as a workaround for now in the generated html pages. Is that OK for now?

But I definitly like the suggestion. The change is probably more invasive as one might suggest, but I would accept a PR for it.

**Comment by matthid** [comment]
The signature of https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L162 needs to changed to return the reason/error and the error must be logged at the call side.

**Comment by matthid** [comment]
Tracked in #370
