### ISSUE TITLE
[question] Splitting a function body with text and evaluation

### ISSUE THREAD

**Issue by incmach** [tpetricek/FSharp.Formatting#373]
Processing the code
```fsharp
let f () =
(**
do print
*)
    printf "%s" "string"
(*** define-output: a ***)
f ()
(*** include-output: a ***)
```
results in "No output has been produced" in place of output. If the comment with text is deleted, the output will be correct. Is such formatting not allowed when using evaluation?

**Comment by tpetricek** [comment]
Sadly, this way of splitting the F# code is not supported - snippets are evaluated separately and so this first evaluates `let f () = ` (which is not syntactically valid) and then it evaluates `printf "%s" "string"`.

I'm not sure how we could detect that a snippet continues, so I'd say it's "by design", but I'm open to better suggestions!
